### ISSUE TITLE
Error in new version of library 1.4.0

### ISSUE THREAD

**Issue by vanslooten** [STEMpedia/Dabble#2]
Compiling gives this error:
`OscilloscopeModule.cpp: In constructor 'OscilloscopeModule::OscilloscopeModule()':
OscilloscopeModule.cpp:7:55: error: 'OSCILLOSCOPE_ID' was not declared in this scope
OscilloscopeModule::OscilloscopeModule():ModuleParent(OSCILLOSCOPE_ID)`

I reverted to version 1.3.0 which has no problems.

**Comment by dhrupal93** [comment]
@vanslooten Thanks for finding out the bug. We have already corrected this in the latest release to be posted on Monday. We have deleted the release of 1.4.0 version, but it is taking time to be updated on Arduino Library Manager.
Sorry, but till then, please use the 1.3.0 version.

**Comment by dhrupal93** [comment]
@vanslooten Now the update 1.4.1 is available. May you try that and report us, if you face any issues.

**Comment by vanslooten** [comment]
Got the update. Compiles fine. Will further test it tomorrow. Thanks for your quick help! I am trying out Dabble in a course. [For instance to remote control this car.](https://home.et.utwente.nl/slootenvanf/2019/04/04/lego-rover-car/)
