### ISSUE TITLE
Errors while compiling using ArduinoIDE

### ISSUE THREAD

**Issue by basilgeo99** [STEMpedia/Dabble#3]
I did as the instructions specified.

But there were several issues :

1.  The zipped file name was invalid and should not have had any '-' or '.' or names beginning with numbers.
2. The file names inside had similar problems 
3. I had to manually change file names to fix this. I did not change the names of any files inside the "src" folder, only the "examples" folder as that is where the problems were arising.

- ![Screenshot from 2019-09-13 00-51-26](https://user-images.githubusercontent.com/47512157/64814425-0f15c480-d5c1-11e9-8876-042ab824cfca.png)
- ![Screenshot from 2019-09-13 00-51-31](https://user-images.githubusercontent.com/47512157/64814445-1f2da400-d5c1-11e9-9b0c-286f365f0630.png)
- ![Screenshot from 2019-09-13 00-51-38](https://user-images.githubusercontent.com/47512157/64814463-25238500-d5c1-11e9-9c9a-7182f7b8d5ef.png)
- ![Screenshot from 2019-09-13 00-51-40](https://user-images.githubusercontent.com/47512157/64814466-2785df00-d5c1-11e9-9ec7-af842ee521c0.png)
- ![Screenshot from 2019-09-13 00-51-44](https://user-images.githubusercontent.com/47512157/64814484-2c4a9300-d5c1-11e9-8655-6e234b22d9cd.png)
- ![Screenshot from 2019-09-13 00-51-46](https://user-images.githubusercontent.com/47512157/64814487-2e145680-d5c1-11e9-9f19-8cd279bbbca9.png)
- ![Screenshot from 2019-09-13 00-51-54](https://user-images.githubusercontent.com/47512157/64814536-3ff5f980-d5c1-11e9-87bc-1da6c572268e.png)

Leaving all the files where they were, I got the following error

![Screenshot from 2019-09-13 00-58-46](https://user-images.githubusercontent.com/47512157/64814787-c3174f80-d5c1-11e9-98af-ec9b2cd8224e.png)

To fix that I moved all the header and cpp files to the folder of my sketch and then the Dabble.h missing error was gone because it was right there but then I ended up getting several other errors a screenshot of which I have attached.

These errors were triggered by `#include<Dabble.h>`

![Screenshot from 2019-09-13 00-44-45](https://user-images.githubusercontent.com/47512157/64814120-7da65280-d5c0-11e9-8a4f-d42387763aff.png)

I use a LinuxOS (Debian 9 Stretch to be specific).

I am really hoping to find a fix for this as soon as possible as I am working on a college related project.

Thankyou.

**Comment by mimansamaheshwari** [comment]
Sorry for the inconvenience caused.
1) We saw that you are facing a problem while library installation.
We request you to update your Arduino IDE to 1.8.5 version (please do not install the latest version as many people are facing some issues with that).
https://www.arduino.cc/download_handler.php?f=/arduino-1.8.5-linux64.tar.xz
or select the correct version from this link: https://www.arduino.cc/en/Main/OldSoftwareReleases#previous

2) Please try using the Arduino Library Manager for installing the Dabble library.
![DabbleLibInstallationFromLibMan1](https://user-images.githubusercontent.com/29648389/64844098-7022b400-d624-11e9-81c9-9e9ef809ac35.png)
![DabbleLibInstallationFromLibMan](https://user-images.githubusercontent.com/29648389/64844097-7022b400-d624-11e9-9add-fe9ede0cc5ac.png)

If you are still facing any issue let us know.

**Comment by basilgeo99** [comment]
Thankyou @mimansamaheshwari for a prompt response.

I have done as you asked and installed ArduinoIDE-1.8.5 after a clean purge of the one I had installed before.
I am now able to successfully import the Dabble library without any error alerts showing up.
(For the time being I have downgraded to Dabble 1.0 . There is no particular reason for this but if there is something I need to keep in mind as I work with this version please do let me know.)

I shall experiment and let you know after I try uploading the code I had uploaded when the errors showed up earlier.

Thankyou again.

**Comment by ranjith-asp** [comment]
> 1. We saw that you are facing a problem while library installation.
>    We request you to update your Arduino IDE to 1.8.5 version (please do not install the latest version as many people are facing some issues with that).
>    https://www.arduino.cc/download_handler.php?f=/arduino-1.8.5-linux64.tar.xz
>    or select the correct version from this link: https://www.arduino.cc/en/Main/OldSoftwareReleases#previous
> 2. Please try using the Arduino Library Manager for installing the Dabble library.
>    ![DabbleLibInstallationFromLibMan1](https://user-images.githubusercontent.com/29648389/64844098-7022b400-d624-11e9-81c9-9e9ef809ac35.png)
>    ![DabbleLibInstallationFromLibMan](https://user-images.githubusercontent.com/29648389/64844097-7022b400-d624-11e9-9add-fe9ede0cc5ac.png)
> 
> If you are still facing any issue let us know.

Though this issue was discussed in Sep 2019, I recently faced issue with Arduino IDE 1.8.16.
Can someone please confirm whether I should still try with v 1.8.5?
In other words, has anyone had any success in installing Dabble library in Arduino IDE that is installed in Raspberry OS (or any other debian distro)??
